// Mocks generated by Mockito 5.0.10 from annotations
// in movies/test/movies_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/src/model/movie.dart' as _i3;
import 'package:movies/src/resources/movies_api_provider.dart' as _i2;
import 'package:movies/src/resources/movies_repository.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeMoviesApiProvider extends _i1.Fake implements _i2.MoviesApiProvider {
}

class _FakeMovie extends _i1.Fake implements _i3.Movie {}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i4.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MoviesApiProvider get moviesApiProvider =>
      (super.noSuchMethod(Invocation.getter(#moviesApiProvider),
          returnValue: _FakeMoviesApiProvider()) as _i2.MoviesApiProvider);
  @override
  _i5.Future<_i3.Movie> fetchAllMovies() =>
      (super.noSuchMethod(Invocation.method(#fetchAllMovies, []),
              returnValue: Future<_i3.Movie>.value(_FakeMovie()))
          as _i5.Future<_i3.Movie>);
  @override
  _i5.Future<_i3.Movie> fetchMovieSearch(String? keywords) =>
      (super.noSuchMethod(Invocation.method(#fetchMovieSearch, [keywords]),
              returnValue: Future<_i3.Movie>.value(_FakeMovie()))
          as _i5.Future<_i3.Movie>);
}
